dfuzzer.conf: suppress BecomeMonitor
Once this method is called dfuzzer can no longer send messages and
bails out with
```
  PASS [M] Introspect
 Interface: org.freedesktop.DBus.Monitoring
  PASS [M] BecomeMonitor
 Interface: org.freedesktop.DBus.Peer
Error: Unable to create proxy for bus name 'org.freedesktop.DBus'.
Exit status: 1
```

https://dbus.freedesktop.org/doc/dbus-specification.html#bus-messages-become-monitor